"use client";

import { useState, useEffect } from "react";
import BlogPostModal from "./BlogPostModal";

interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string;
  featuredImage?: string;
  status: string;
  contentType?: string;
  authorName?: string;
  publishedAt?: string;
  scheduledAt?: string;
  readTimeMinutes?: number;
  viewCount?: number;
  isAutoGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
  categoryId?: number;
  categoryName?: string;
  destinationId?: number;
  destinationName?: string;
}

interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  description?: string;
  color: string;
  isActive: boolean;
}

interface Destination {
  id: number;
  name: string;
}

interface BlogTabProps {
  destinations: Destination[];
}

const CONTENT_TYPES = [
  { value: "destination_guide", label: "Destination Guide" },
  { value: "travel_tips", label: "Travel Tips" },
  { value: "packing_list", label: "Packing List" },
  { value: "cultural_insights", label: "Cultural Insights" },
  { value: "seasonal_content", label: "Seasonal Content" },
  { value: "trip_report", label: "Trip Report" },
];

const STATUS_OPTIONS = [
  { value: "all", label: "All Status" },
  { value: "draft", label: "Draft" },
  { value: "scheduled", label: "Scheduled" },
  { value: "published", label: "Published" },
  { value: "archived", label: "Archived" },
];

export default function BlogTab({ destinations }: BlogTabProps) {
  const [activeSubTab, setActiveSubTab] = useState<"posts" | "categories" | "schedule" | "analytics">("posts");
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [categories, setCategories] = useState<BlogCategory[]>([]);
  const [loading, setLoading] = useState(true);
  const [showPostModal, setShowPostModal] = useState(false);
  const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
  const [showCategoryModal, setShowCategoryModal] = useState(false);
  const [editingCategory, setEditingCategory] = useState<BlogCategory | null>(null);

  // Filters
  const [statusFilter, setStatusFilter] = useState("all");
  const [categoryFilter, setCategoryFilter] = useState<number | null>(null);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    fetchCategories();
    if (activeSubTab === "posts" || activeSubTab === "schedule") {
      fetchPosts();
    }
  }, [activeSubTab]);

  const fetchPosts = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter !== "all") params.set("status", statusFilter);
      if (categoryFilter) params.set("categoryId", String(categoryFilter));
      if (searchQuery) params.set("search", searchQuery);

      const res = await fetch(`/api/admin/blog/posts?${params}`);
      const data = await res.json();
      setPosts(data.posts || []);
    } catch (error) {
      console.error("Error fetching blog posts:", error);
    } finally {
      setLoading(false);
    }
  };

  const fetchCategories = async () => {
    try {
      const res = await fetch("/api/admin/blog/categories");
      const data = await res.json();
      setCategories(data.categories || []);
    } catch (error) {
      console.error("Error fetching categories:", error);
    }
  };

  const deletePost = async (postId: number) => {
    if (!confirm("Are you sure you want to delete this post?")) return;
    try {
      await fetch(`/api/admin/blog/posts/${postId}`, { method: "DELETE" });
      fetchPosts();
    } catch (error) {
      console.error("Error deleting post:", error);
    }
  };

  const updatePostStatus = async (postId: number, status: string) => {
    try {
      await fetch(`/api/admin/blog/posts/${postId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      });
      fetchPosts();
    } catch (error) {
      console.error("Error updating post status:", error);
    }
  };

  const saveCategory = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingCategory) return;

    try {
      if (editingCategory.id) {
        await fetch("/api/admin/blog/categories", {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(editingCategory),
        });
      } else {
        await fetch("/api/admin/blog/categories", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(editingCategory),
        });
      }
      setShowCategoryModal(false);
      setEditingCategory(null);
      fetchCategories();
    } catch (error) {
      console.error("Error saving category:", error);
    }
  };

  const deleteCategory = async (categoryId: number) => {
    if (!confirm("Are you sure you want to delete this category?")) return;
    try {
      await fetch(`/api/admin/blog/categories?id=${categoryId}`, { method: "DELETE" });
      fetchCategories();
    } catch (error) {
      console.error("Error deleting category:", error);
    }
  };

  const getStatusColor = (status: string) => {
    const colors: Record<string, string> = {
      draft: "bg-slate-500/20 text-slate-400",
      scheduled: "bg-yellow-500/20 text-yellow-400",
      published: "bg-green-500/20 text-green-400",
      archived: "bg-red-500/20 text-red-400",
    };
    return colors[status] || "bg-slate-500/20 text-slate-400";
  };

  const getContentTypeLabel = (type?: string) => {
    return CONTENT_TYPES.find((t) => t.value === type)?.label || type || "Unknown";
  };

  // Stats
  const stats = {
    total: posts.length,
    published: posts.filter((p) => p.status === "published").length,
    scheduled: posts.filter((p) => p.status === "scheduled").length,
    draft: posts.filter((p) => p.status === "draft").length,
    totalViews: posts.reduce((sum, p) => sum + (p.viewCount || 0), 0),
  };

  // Scheduled posts for calendar
  const scheduledPosts = posts
    .filter((p) => p.status === "scheduled" && p.scheduledAt)
    .sort((a, b) => new Date(a.scheduledAt!).getTime() - new Date(b.scheduledAt!).getTime());

  return (
    <div>
      {/* Sub-tabs */}
      <div className="flex gap-2 mb-6 border-b border-slate-700 pb-4">
        {[
          { key: "posts", label: "All Posts" },
          { key: "categories", label: "Categories" },
          { key: "schedule", label: "Content Calendar" },
          { key: "analytics", label: "Analytics" },
        ].map((tab) => (
          <button
            key={tab.key}
            onClick={() => setActiveSubTab(tab.key as typeof activeSubTab)}
            className={`px-4 py-2 rounded-t text-sm transition-colors ${
              activeSubTab === tab.key
                ? "bg-emerald-600 text-white"
                : "bg-slate-800 text-slate-400 hover:bg-slate-700"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Posts Tab */}
      {activeSubTab === "posts" && (
        <div>
          {/* Stats Overview */}
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-6">
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-3">
              <div className="text-xs text-slate-400 mb-1">Total Posts</div>
              <div className="text-xl font-bold text-white">{stats.total}</div>
            </div>
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-3">
              <div className="text-xs text-slate-400 mb-1">Published</div>
              <div className="text-xl font-bold text-green-400">{stats.published}</div>
            </div>
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-3">
              <div className="text-xs text-slate-400 mb-1">Scheduled</div>
              <div className="text-xl font-bold text-yellow-400">{stats.scheduled}</div>
            </div>
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-3">
              <div className="text-xs text-slate-400 mb-1">Drafts</div>
              <div className="text-xl font-bold text-slate-400">{stats.draft}</div>
            </div>
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-3">
              <div className="text-xs text-slate-400 mb-1">Total Views</div>
              <div className="text-xl font-bold text-blue-400">{stats.totalViews.toLocaleString()}</div>
            </div>
          </div>

          {/* Filters and Actions */}
          <div className="flex flex-wrap gap-3 mb-4">
            <input
              type="text"
              placeholder="Search posts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && fetchPosts()}
              className="bg-slate-800 border border-slate-700 rounded px-3 py-2 text-white text-sm w-64"
            />
            <select
              value={statusFilter}
              onChange={(e) => {
                setStatusFilter(e.target.value);
                setTimeout(fetchPosts, 0);
              }}
              className="bg-slate-800 border border-slate-700 rounded px-3 py-2 text-white text-sm"
            >
              {STATUS_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
            <select
              value={categoryFilter || ""}
              onChange={(e) => {
                setCategoryFilter(e.target.value ? parseInt(e.target.value) : null);
                setTimeout(fetchPosts, 0);
              }}
              className="bg-slate-800 border border-slate-700 rounded px-3 py-2 text-white text-sm"
            >
              <option value="">All Categories</option>
              {categories.map((cat) => (
                <option key={cat.id} value={cat.id}>
                  {cat.name}
                </option>
              ))}
            </select>

            <div className="flex-1" />

            <button
              onClick={() => {
                setEditingPost(null);
                setShowPostModal(true);
              }}
              className="bg-emerald-600 hover:bg-emerald-700 px-4 py-2 rounded text-white text-sm"
            >
              + Create Post
            </button>
          </div>

          {/* Posts List */}
          {loading ? (
            <div className="text-center py-8 text-slate-400">Loading posts...</div>
          ) : posts.length === 0 ? (
            <div className="text-center py-8 text-slate-400">
              No blog posts yet. Click &quot;Create Post&quot; to get started.
            </div>
          ) : (
            <div className="space-y-3">
              {posts.map((post) => (
                <div
                  key={post.id}
                  className="bg-slate-800 border border-slate-700 rounded-lg p-4 hover:border-slate-600 transition-colors"
                >
                  <div className="flex items-start gap-4">
                    {/* Thumbnail */}
                    {post.featuredImage ? (
                      <img
                        src={post.featuredImage}
                        alt={post.title}
                        className="w-20 h-20 object-cover rounded"
                      />
                    ) : (
                      <div className="w-20 h-20 bg-slate-700 rounded flex items-center justify-center text-slate-500 text-xs">
                        No Image
                      </div>
                    )}

                    {/* Content */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <h3 className="font-semibold text-white text-lg truncate">{post.title}</h3>
                          <div className="flex items-center gap-2 mt-1 flex-wrap">
                            <span className={`px-2 py-0.5 rounded text-xs ${getStatusColor(post.status)}`}>
                              {post.status}
                            </span>
                            {post.categoryName && (
                              <span className="px-2 py-0.5 rounded text-xs bg-indigo-500/20 text-indigo-400">
                                {post.categoryName}
                              </span>
                            )}
                            {post.contentType && (
                              <span className="text-xs text-slate-500">
                                {getContentTypeLabel(post.contentType)}
                              </span>
                            )}
                            {post.isAutoGenerated && (
                              <span className="px-2 py-0.5 rounded text-xs bg-purple-500/20 text-purple-400">
                                AI Generated
                              </span>
                            )}
                          </div>
                        </div>

                        <div className="flex items-center gap-2 shrink-0">
                          {post.status === "draft" && (
                            <button
                              onClick={() => updatePostStatus(post.id, "published")}
                              className="text-green-400 hover:text-green-300 text-sm"
                            >
                              Publish
                            </button>
                          )}
                          <button
                            onClick={() => {
                              setEditingPost(post);
                              setShowPostModal(true);
                            }}
                            className="text-slate-400 hover:text-white text-sm"
                          >
                            Edit
                          </button>
                          <button
                            onClick={() => deletePost(post.id)}
                            className="text-red-400 hover:text-red-300 text-sm"
                          >
                            Delete
                          </button>
                        </div>
                      </div>

                      {post.excerpt && (
                        <p className="text-slate-400 text-sm mt-2 line-clamp-2">{post.excerpt}</p>
                      )}

                      <div className="flex items-center gap-4 mt-3 text-xs text-slate-500">
                        {post.authorName && <span>By {post.authorName}</span>}
                        {post.readTimeMinutes && <span>{post.readTimeMinutes} min read</span>}
                        {post.viewCount !== undefined && (
                          <span>{post.viewCount.toLocaleString()} views</span>
                        )}
                        {post.publishedAt && (
                          <span>Published {new Date(post.publishedAt).toLocaleDateString()}</span>
                        )}
                        {post.scheduledAt && post.status === "scheduled" && (
                          <span className="text-yellow-400">
                            Scheduled for {new Date(post.scheduledAt).toLocaleDateString()}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Categories Tab */}
      {activeSubTab === "categories" && (
        <div>
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-semibold text-white">Blog Categories</h3>
            <button
              onClick={() => {
                setEditingCategory({
                  id: 0,
                  name: "",
                  slug: "",
                  color: "#3b82f6",
                  isActive: true,
                });
                setShowCategoryModal(true);
              }}
              className="bg-emerald-600 hover:bg-emerald-700 px-4 py-2 rounded text-white text-sm"
            >
              + Add Category
            </button>
          </div>

          {categories.length === 0 ? (
            <div className="text-center py-8 text-slate-400">
              No categories yet. Add categories to organize your blog posts.
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {categories.map((category) => (
                <div
                  key={category.id}
                  className={`bg-slate-800 border rounded-lg p-4 ${
                    category.isActive ? "border-slate-700" : "border-slate-700/50 opacity-60"
                  }`}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex items-center gap-3">
                      <div
                        className="w-4 h-4 rounded"
                        style={{ backgroundColor: category.color }}
                      />
                      <div>
                        <h4 className="font-semibold text-white">{category.name}</h4>
                        <span className="text-xs text-slate-500">/{category.slug}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => {
                          setEditingCategory(category);
                          setShowCategoryModal(true);
                        }}
                        className="text-slate-400 hover:text-white text-sm"
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => deleteCategory(category.id)}
                        className="text-red-400 hover:text-red-300 text-sm"
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                  {category.description && (
                    <p className="text-sm text-slate-400 mt-2">{category.description}</p>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Schedule Tab */}
      {activeSubTab === "schedule" && (
        <div>
          <h3 className="text-lg font-semibold text-white mb-4">Content Calendar</h3>

          {scheduledPosts.length === 0 ? (
            <div className="text-center py-8 text-slate-400">
              No scheduled posts. Schedule posts to see them here.
            </div>
          ) : (
            <div className="space-y-4">
              {scheduledPosts.map((post) => (
                <div
                  key={post.id}
                  className="bg-slate-800 border border-yellow-500/30 rounded-lg p-4"
                >
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-yellow-400 text-sm font-medium mb-1">
                        {post.scheduledAt &&
                          new Date(post.scheduledAt).toLocaleDateString("en-US", {
                            weekday: "long",
                            year: "numeric",
                            month: "long",
                            day: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                      </div>
                      <h4 className="font-semibold text-white">{post.title}</h4>
                      <div className="flex items-center gap-2 mt-1">
                        {post.categoryName && (
                          <span className="text-xs text-slate-400">{post.categoryName}</span>
                        )}
                        {post.contentType && (
                          <span className="text-xs text-slate-500">
                            • {getContentTypeLabel(post.contentType)}
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => updatePostStatus(post.id, "published")}
                        className="text-green-400 hover:text-green-300 text-sm"
                      >
                        Publish Now
                      </button>
                      <button
                        onClick={() => {
                          setEditingPost(post);
                          setShowPostModal(true);
                        }}
                        className="text-slate-400 hover:text-white text-sm"
                      >
                        Edit
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Analytics Tab */}
      {activeSubTab === "analytics" && (
        <div>
          <h3 className="text-lg font-semibold text-white mb-4">Blog Analytics</h3>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Top Performing Posts */}
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-4">
              <h4 className="text-sm font-semibold text-slate-300 mb-4">Top Performing Posts</h4>
              {posts.length === 0 ? (
                <div className="text-center py-4 text-slate-500 text-sm">No data available</div>
              ) : (
                <div className="space-y-3">
                  {posts
                    .filter((p) => p.status === "published")
                    .sort((a, b) => (b.viewCount || 0) - (a.viewCount || 0))
                    .slice(0, 5)
                    .map((post, idx) => (
                      <div
                        key={post.id}
                        className="flex items-center justify-between bg-slate-900/50 rounded p-3"
                      >
                        <div className="flex items-center gap-3">
                          <span className="text-slate-500 text-sm w-4">{idx + 1}.</span>
                          <span className="text-white text-sm truncate max-w-[200px]">
                            {post.title}
                          </span>
                        </div>
                        <span className="text-blue-400 font-bold text-sm">
                          {(post.viewCount || 0).toLocaleString()} views
                        </span>
                      </div>
                    ))}
                </div>
              )}
            </div>

            {/* Posts by Category */}
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-4">
              <h4 className="text-sm font-semibold text-slate-300 mb-4">Posts by Category</h4>
              {categories.length === 0 ? (
                <div className="text-center py-4 text-slate-500 text-sm">No data available</div>
              ) : (
                <div className="space-y-3">
                  {categories.map((category) => {
                    const count = posts.filter((p) => p.categoryId === category.id).length;
                    const percentage =
                      posts.length > 0 ? Math.round((count / posts.length) * 100) : 0;
                    return (
                      <div key={category.id}>
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-white text-sm">{category.name}</span>
                          <span className="text-slate-400 text-sm">{count} posts</span>
                        </div>
                        <div className="w-full bg-slate-700 rounded-full h-2">
                          <div
                            className="h-2 rounded-full transition-all"
                            style={{
                              width: `${percentage}%`,
                              backgroundColor: category.color,
                            }}
                          />
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Content Type Distribution */}
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-4">
              <h4 className="text-sm font-semibold text-slate-300 mb-4">Content Type Distribution</h4>
              <div className="space-y-3">
                {CONTENT_TYPES.map((type) => {
                  const count = posts.filter((p) => p.contentType === type.value).length;
                  return (
                    <div key={type.value} className="flex items-center justify-between">
                      <span className="text-white text-sm">{type.label}</span>
                      <span className="text-slate-400 font-bold">{count}</span>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Publishing Frequency */}
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-4">
              <h4 className="text-sm font-semibold text-slate-300 mb-4">AI vs Manual Content</h4>
              <div className="flex items-center justify-center h-32">
                <div className="text-center">
                  <div className="flex items-center gap-8">
                    <div>
                      <div className="text-3xl font-bold text-purple-400">
                        {posts.filter((p) => p.isAutoGenerated).length}
                      </div>
                      <div className="text-xs text-slate-500">AI Generated</div>
                    </div>
                    <div className="text-slate-600 text-2xl">/</div>
                    <div>
                      <div className="text-3xl font-bold text-cyan-400">
                        {posts.filter((p) => !p.isAutoGenerated).length}
                      </div>
                      <div className="text-xs text-slate-500">Manual</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Post Modal */}
      {showPostModal && (
        <BlogPostModal
          post={editingPost}
          categories={categories}
          destinations={destinations}
          onClose={() => {
            setShowPostModal(false);
            setEditingPost(null);
          }}
          onSave={() => {
            setShowPostModal(false);
            setEditingPost(null);
            fetchPosts();
          }}
        />
      )}

      {/* Category Modal */}
      {showCategoryModal && editingCategory && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50">
          <div className="bg-slate-900 border border-slate-700 rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold text-white mb-4">
              {editingCategory.id ? "Edit Category" : "Add Category"}
            </h3>
            <form onSubmit={saveCategory} className="space-y-4">
              <div>
                <label className="block text-xs text-slate-400 mb-1">Name *</label>
                <input
                  type="text"
                  required
                  value={editingCategory.name}
                  onChange={(e) =>
                    setEditingCategory({ ...editingCategory, name: e.target.value })
                  }
                  className="w-full bg-slate-800 border border-slate-700 rounded px-3 py-2 text-white text-sm"
                  placeholder="Category name"
                />
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">Slug</label>
                <input
                  type="text"
                  value={editingCategory.slug}
                  onChange={(e) =>
                    setEditingCategory({ ...editingCategory, slug: e.target.value })
                  }
                  className="w-full bg-slate-800 border border-slate-700 rounded px-3 py-2 text-white text-sm"
                  placeholder="Auto-generated if empty"
                />
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">Description</label>
                <textarea
                  value={editingCategory.description || ""}
                  onChange={(e) =>
                    setEditingCategory({ ...editingCategory, description: e.target.value })
                  }
                  className="w-full bg-slate-800 border border-slate-700 rounded px-3 py-2 text-white text-sm"
                  rows={2}
                />
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">Color</label>
                <input
                  type="color"
                  value={editingCategory.color}
                  onChange={(e) =>
                    setEditingCategory({ ...editingCategory, color: e.target.value })
                  }
                  className="w-16 h-8 bg-slate-800 border border-slate-700 rounded"
                />
              </div>
              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="categoryActive"
                  checked={editingCategory.isActive}
                  onChange={(e) =>
                    setEditingCategory({ ...editingCategory, isActive: e.target.checked })
                  }
                  className="rounded bg-slate-800 border-slate-700"
                />
                <label htmlFor="categoryActive" className="text-sm text-slate-300">
                  Active
                </label>
              </div>
              <div className="flex justify-end gap-3 pt-4 border-t border-slate-700">
                <button
                  type="button"
                  onClick={() => {
                    setShowCategoryModal(false);
                    setEditingCategory(null);
                  }}
                  className="px-4 py-2 text-slate-400 hover:text-white text-sm"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="bg-emerald-600 hover:bg-emerald-700 px-4 py-2 rounded text-white text-sm"
                >
                  {editingCategory.id ? "Update" : "Create"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
