import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { blogPosts, blogCategories, destinations } from "@/db/schema";
import { eq, desc, ilike, and, or, sql } from "drizzle-orm";

export const dynamic = "force-dynamic";

// GET - List all blog posts with filters
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const status = searchParams.get("status");
    const categoryId = searchParams.get("categoryId");
    const search = searchParams.get("search");
    const limit = parseInt(searchParams.get("limit") || "50");
    const offset = parseInt(searchParams.get("offset") || "0");

    // Build conditions
    const conditions = [];

    if (status) {
      conditions.push(eq(blogPosts.status, status));
    }

    if (categoryId) {
      conditions.push(eq(blogPosts.categoryId, parseInt(categoryId)));
    }

    if (search) {
      conditions.push(
        or(
          ilike(blogPosts.title, `%${search}%`),
          ilike(blogPosts.excerpt, `%${search}%`)
        )
      );
    }

    // Get posts with category and destination info
    const posts = await db
      .select({
        id: blogPosts.id,
        title: blogPosts.title,
        slug: blogPosts.slug,
        excerpt: blogPosts.excerpt,
        featuredImage: blogPosts.featuredImage,
        status: blogPosts.status,
        contentType: blogPosts.contentType,
        authorName: blogPosts.authorName,
        publishedAt: blogPosts.publishedAt,
        scheduledAt: blogPosts.scheduledAt,
        readTimeMinutes: blogPosts.readTimeMinutes,
        viewCount: blogPosts.viewCount,
        isAutoGenerated: blogPosts.isAutoGenerated,
        createdAt: blogPosts.createdAt,
        updatedAt: blogPosts.updatedAt,
        categoryId: blogPosts.categoryId,
        categoryName: blogCategories.name,
        categorySlug: blogCategories.slug,
        destinationId: blogPosts.destinationId,
        destinationCountry: destinations.country,
      })
      .from(blogPosts)
      .leftJoin(blogCategories, eq(blogPosts.categoryId, blogCategories.id))
      .leftJoin(destinations, eq(blogPosts.destinationId, destinations.id))
      .where(conditions.length > 0 ? and(...conditions) : undefined)
      .orderBy(desc(blogPosts.createdAt))
      .limit(limit)
      .offset(offset);

    // Get total count
    const [{ count }] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(blogPosts)
      .where(conditions.length > 0 ? and(...conditions) : undefined);

    return NextResponse.json({
      success: true,
      posts,
      total: count,
      limit,
      offset,
    });
  } catch (error) {
    console.error("Error fetching blog posts:", error);
    return NextResponse.json(
      { error: "Failed to fetch blog posts" },
      { status: 500 }
    );
  }
}

// POST - Create new blog post
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      title,
      slug,
      content,
      excerpt,
      categoryId,
      destinationId,
      featuredImage,
      featuredImageAlt,
      gallery,
      metaTitle,
      metaDescription,
      keywords,
      tags,
      status = "draft",
      authorName = "CuratedAscents Team",
      scheduledAt,
      contentType = "destination_guide",
      readTimeMinutes,
      isAutoGenerated = false,
      promptUsed,
    } = body;

    if (!title || !content) {
      return NextResponse.json(
        { error: "Missing required fields: title, content" },
        { status: 400 }
      );
    }

    // Generate slug if not provided
    const finalSlug = slug || generateSlug(title);

    // Check if slug already exists
    const existingPost = await db
      .select({ id: blogPosts.id })
      .from(blogPosts)
      .where(eq(blogPosts.slug, finalSlug))
      .limit(1);

    if (existingPost.length > 0) {
      return NextResponse.json(
        { error: "A post with this slug already exists" },
        { status: 400 }
      );
    }

    const [newPost] = await db
      .insert(blogPosts)
      .values({
        title,
        slug: finalSlug,
        content,
        excerpt: excerpt || generateExcerpt(content),
        categoryId: categoryId || null,
        destinationId: destinationId || null,
        featuredImage,
        featuredImageAlt,
        gallery,
        metaTitle: metaTitle || title,
        metaDescription: metaDescription || excerpt || generateExcerpt(content),
        keywords,
        tags,
        status,
        authorName,
        scheduledAt: scheduledAt ? new Date(scheduledAt) : null,
        publishedAt: status === "published" ? new Date() : null,
        contentType,
        readTimeMinutes: readTimeMinutes || calculateReadTime(content),
        isAutoGenerated,
        promptUsed,
      })
      .returning();

    return NextResponse.json({
      success: true,
      post: newPost,
    });
  } catch (error) {
    console.error("Error creating blog post:", error);
    return NextResponse.json(
      { error: "Failed to create blog post" },
      { status: 500 }
    );
  }
}

// Helper functions
function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function generateExcerpt(content: string, maxLength: number = 200): string {
  // Strip markdown formatting
  const stripped = content
    .replace(/#+\s/g, "")
    .replace(/\*\*/g, "")
    .replace(/\*/g, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/\n+/g, " ")
    .trim();

  if (stripped.length <= maxLength) return stripped;
  return stripped.substring(0, maxLength).trim() + "...";
}

function calculateReadTime(content: string): number {
  const wordsPerMinute = 200;
  const wordCount = content.split(/\s+/).length;
  return Math.ceil(wordCount / wordsPerMinute);
}
