// Sample seed data for all tables
// Run via API: http://localhost:3000/api/seed-all

export const sampleSuppliers = [
    { name: "Dwarika's Group", type: 'hotel', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Yeti Airlines', type: 'airline', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Himalayan Guides', type: 'guide_company', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Adventure Consultants', type: 'adventure_company', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Simrik Air', type: 'helicopter', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Bhutan Tourism Corp', type: 'dmc', country: 'Bhutan', city: 'Thimphu' },
  ];
  
  export const sampleDestinations = [
    { country: 'Nepal', region: 'Kathmandu Valley', city: 'Kathmandu', altitude: 1400 },
    { country: 'Nepal', region: 'Kathmandu Valley', city: 'Bhaktapur', altitude: 1400 },
    { country: 'Nepal', region: 'Pokhara Valley', city: 'Pokhara', altitude: 827 },
    { country: 'Nepal', region: 'Everest Region', city: 'Lukla', altitude: 2860 },
    { country: 'Nepal', region: 'Everest Region', city: 'Namche Bazaar', altitude: 3440 },
    { country: 'Nepal', region: 'Annapurna Region', city: 'Jomsom', altitude: 2720 },
    { country: 'Tibet', region: 'Central Tibet', city: 'Lhasa', altitude: 3650 },
    { country: 'Bhutan', region: 'Western Bhutan', city: 'Thimphu', altitude: 2320 },
    { country: 'Bhutan', region: 'Western Bhutan', city: 'Paro', altitude: 2200 },
    { country: 'India', region: 'Sikkim', city: 'Gangtok', altitude: 1650 },
  ];
  
  export const sampleHotels = [
    {
      name: "Dwarika's Hotel",
      starRating: 5,
      category: 'Heritage Luxury',
      destinationCity: 'Kathmandu',
      description: 'Award-winning heritage hotel with traditional Newari architecture',
      amenities: ['spa', 'pool', 'gym', 'wifi', 'restaurant', 'bar'],
    },
    {
      name: 'Hotel Yak & Yeti',
      starRating: 5,
      category: 'Luxury',
      destinationCity: 'Kathmandu',
      description: 'Iconic 5-star hotel in the heart of Kathmandu',
      amenities: ['spa', 'pool', 'gym', 'wifi', 'casino', 'restaurants'],
    },
    {
      name: 'Tiger Mountain Pokhara Lodge',
      starRating: 4,
      category: 'Boutique Lodge',
      destinationCity: 'Pokhara',
      description: 'Stunning mountain views with eco-luxury experience',
      amenities: ['infinity pool', 'spa', 'yoga', 'organic garden'],
    },
    {
      name: 'Everest View Hotel',
      starRating: 3,
      category: 'Mountain Lodge',
      destinationCity: 'Namche Bazaar',
      description: 'Highest placed hotel in the world with Everest views',
      amenities: ['oxygen', 'heating', 'restaurant', 'wifi'],
    },
  ];
  
  export const sampleHotelRates = [
    // Dwarika's Hotel rates
    {
      hotelName: "Dwarika's Hotel",
      roomType: 'Heritage Deluxe',
      mealPlan: 'CP',
      costDouble: 280,
      sellDouble: 420,
      costSingle: 250,
      sellSingle: 375,
      costExtraBed: 60,
      sellExtraBed: 90,
      inclusions: 'Breakfast buffet, WiFi, Gym access, Welcome drink',
    },
    {
      hotelName: "Dwarika's Hotel",
      roomType: 'Heritage Suite',
      mealPlan: 'MAP',
      costDouble: 450,
      sellDouble: 675,
      costSingle: 400,
      sellSingle: 600,
      costExtraBed: 80,
      sellExtraBed: 120,
      inclusions: 'Breakfast & Dinner, WiFi, Spa access, Butler service',
    },
    // Tiger Mountain rates
    {
      hotelName: 'Tiger Mountain Pokhara Lodge',
      roomType: 'Deluxe Cottage',
      mealPlan: 'AP',
      costDouble: 320,
      sellDouble: 480,
      costSingle: 280,
      sellSingle: 420,
      costExtraBed: 70,
      sellExtraBed: 105,
      inclusions: 'All meals, Yoga sessions, Nature walks, WiFi',
    },
  ];
  
  export const sampleTransportation = [
    {
      vehicleType: 'sedan',
      vehicleName: 'Toyota Corolla',
      capacity: 3,
      routeFrom: 'Kathmandu',
      routeTo: 'Pokhara',
      distanceKm: 200,
      durationHours: 6,
      costPrice: 120,
      sellPrice: 180,
      inclusions: 'Fuel, driver, tolls, parking',
    },
    {
      vehicleType: 'suv',
      vehicleName: 'Toyota Fortuner',
      capacity: 5,
      routeFrom: 'Kathmandu',
      routeTo: 'Chitwan',
      distanceKm: 150,
      durationHours: 5,
      costPrice: 150,
      sellPrice: 225,
      inclusions: 'Fuel, driver, tolls, parking',
    },
    {
      vehicleType: 'hiace',
      vehicleName: 'Toyota Hiace',
      capacity: 12,
      routeFrom: 'Kathmandu',
      routeTo: 'Pokhara',
      distanceKm: 200,
      durationHours: 6,
      costPrice: 200,
      sellPrice: 300,
      inclusions: 'Fuel, driver, tolls, parking',
    },
    {
      vehicleType: 'land_cruiser',
      vehicleName: 'Toyota Land Cruiser',
      capacity: 5,
      routeFrom: 'Kathmandu',
      routeTo: 'Kodari Border',
      distanceKm: 120,
      durationHours: 4,
      costPrice: 200,
      sellPrice: 300,
      inclusions: 'Fuel, driver, tolls, permits assistance',
    },
  ];
  
  export const sampleGuides = [
    {
      guideType: 'city',
      destination: 'Kathmandu',
      languages: ['English', 'French', 'German'],
      specializations: ['Heritage', 'Buddhism', 'Hinduism'],
      experienceYears: 15,
      costPerDay: 40,
      sellPerDay: 60,
      inclusions: 'Guide service only',
      exclusions: 'Entrance fees, meals, transport',
      maxGroupSize: 15,
    },
    {
      guideType: 'trekking',
      destination: 'Everest Region',
      languages: ['English', 'Spanish'],
      specializations: ['Everest', 'High Altitude'],
      experienceYears: 12,
      costPerDay: 50,
      sellPerDay: 75,
      inclusions: 'Guide meals, accommodation, insurance',
      exclusions: 'Client meals, permits',
      maxGroupSize: 12,
    },
    {
      guideType: 'trekking',
      destination: 'Annapurna Region',
      languages: ['English', 'Japanese'],
      specializations: ['Annapurna', 'Photography'],
      experienceYears: 10,
      costPerDay: 45,
      sellPerDay: 68,
      inclusions: 'Guide meals, accommodation, insurance',
      exclusions: 'Client meals, permits',
      maxGroupSize: 10,
    },
  ];
  
  export const samplePorters = [
    {
      region: 'Everest Region',
      maxWeightKg: 25,
      costPerDay: 20,
      sellPerDay: 30,
      inclusions: 'Porter meals, accommodation, insurance',
      exclusions: 'Tips',
    },
    {
      region: 'Annapurna Region',
      maxWeightKg: 25,
      costPerDay: 18,
      sellPerDay: 27,
      inclusions: 'Porter meals, accommodation, insurance',
      exclusions: 'Tips',
    },
  ];
  
  export const sampleFlights = [
    {
      airlineName: 'Buddha Air',
      flightSector: 'KTM-LUA',
      departureCity: 'Kathmandu',
      arrivalCity: 'Lukla',
      flightDuration: '35 mins',
      baggageAllowanceKg: 15,
      costPrice: 180,
      sellPrice: 220,
      inclusions: '15kg baggage, taxes',
    },
    {
      airlineName: 'Yeti Airlines',
      flightSector: 'KTM-PKR',
      departureCity: 'Kathmandu',
      arrivalCity: 'Pokhara',
      flightDuration: '25 mins',
      baggageAllowanceKg: 20,
      costPrice: 100,
      sellPrice: 130,
      inclusions: '20kg baggage, taxes',
    },
    {
      airlineName: 'Buddha Air',
      flightSector: 'KTM-BWA',
      departureCity: 'Kathmandu',
      arrivalCity: 'Bhairahawa',
      flightDuration: '30 mins',
      baggageAllowanceKg: 20,
      costPrice: 120,
      sellPrice: 150,
      inclusions: '20kg baggage, taxes',
    },
  ];
  
  export const sampleHelicopterSharing = [
    {
      routeName: 'Everest Base Camp Heli Tour',
      routeFrom: 'Kathmandu',
      routeTo: 'Everest Base Camp',
      flightDuration: '4-5 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      seatsAvailable: 5,
      minPassengers: 4,
      costPerSeat: 900,
      sellPerSeat: 1100,
      inclusions: 'Hotel pickup, Kalapatthar landing, breakfast at Everest View Hotel, all permits',
    },
    {
      routeName: 'Annapurna Base Camp Heli Tour',
      routeFrom: 'Pokhara',
      routeTo: 'Annapurna Base Camp',
      flightDuration: '2-3 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      seatsAvailable: 5,
      minPassengers: 4,
      costPerSeat: 600,
      sellPerSeat: 750,
      inclusions: 'Hotel pickup, ABC landing, all permits',
    },
  ];
  
  export const sampleHelicopterCharter = [
    {
      routeName: 'Everest Base Camp Charter',
      routeFrom: 'Kathmandu',
      routeTo: 'Everest Base Camp',
      flightDuration: '4-5 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      maxPassengers: 5,
      costPerCharter: 4000,
      sellPerCharter: 5200,
      inclusions: 'Exclusive charter, Kalapatthar landing, breakfast at Everest View Hotel, all permits',
    },
    {
      routeName: 'Langtang Valley Charter',
      routeFrom: 'Kathmandu',
      routeTo: 'Kyanjin Gompa',
      flightDuration: '2-3 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      maxPassengers: 5,
      costPerCharter: 2800,
      sellPerCharter: 3600,
      inclusions: 'Exclusive charter, monastery visit, all permits',
    },
  ];
  
  export const samplePermitsFees = [
    {
      name: 'TIMS Card',
      type: 'permit',
      country: 'Nepal',
      applicableTo: 'foreigners',
      costPrice: 20,
      sellPrice: 25,
      description: 'Trekkers Information Management System card required for all treks',
    },
    {
      name: 'Sagarmatha National Park Entry',
      type: 'entrance_fee',
      country: 'Nepal',
      region: 'Everest',
      applicableTo: 'foreigners',
      costPrice: 30,
      sellPrice: 35,
      description: 'Entry permit for Everest region (Sagarmatha National Park)',
    },
    {
      name: 'Annapurna Conservation Area Permit',
      type: 'conservation',
      country: 'Nepal',
      region: 'Annapurna',
      applicableTo: 'foreigners',
      costPrice: 30,
      sellPrice: 35,
      description: 'ACAP permit for Annapurna region trekking',
    },
    {
      name: 'Tibet Travel Permit',
      type: 'permit',
      country: 'Tibet',
      applicableTo: 'foreigners',
      costPrice: 100,
      sellPrice: 120,
      description: 'Required permit for foreigners to visit Tibet',
      processingTime: '15-20 days',
    },
  ];
  
  export const sampleMiscellaneous = [
    {
      name: 'Nepalese Dinner with Cultural Show',
      category: 'dining',
      destination: 'Kathmandu',
      description: 'Traditional Nepali cuisine with live music and dance performances',
      duration: '3 hours',
      costPrice: 35,
      sellPrice: 55,
      priceType: 'per_person',
      inclusions: 'Multi-course dinner, cultural performances, welcome drink',
    },
    {
      name: 'Dinner with Local Family',
      category: 'experience',
      destination: 'Kathmandu',
      description: 'Authentic home-cooked meal with a local Newari family',
      duration: '3-4 hours',
      costPrice: 40,
      sellPrice: 65,
      priceType: 'per_person',
      minParticipants: 2,
      inclusions: 'Home-cooked meal, cooking demonstration, cultural exchange',
    },
    {
      name: 'Celebrity Chef Dinner',
      category: 'dining',
      destination: 'Kathmandu',
      description: 'Exclusive dining experience with renowned local chef',
      duration: '4 hours',
      costPrice: 120,
      sellPrice: 180,
      priceType: 'per_person',
      minParticipants: 4,
      inclusions: '7-course tasting menu, wine pairing, meet the chef',
    },
    {
      name: 'Phewa Lake Boating',
      category: 'activity',
      destination: 'Pokhara',
      description: 'Scenic rowboat ride on Phewa Lake with mountain views',
      duration: '1-2 hours',
      costPrice: 10,
      sellPrice: 18,
      priceType: 'per_person',
      inclusions: 'Boat rental, life jacket',
    },
    {
      name: 'Hot Air Balloon Flight',
      category: 'activity',
      destination: 'Pokhara',
      description: 'Sunrise balloon flight with Himalayan panorama',
      duration: '1 hour flight',
      costPrice: 180,
      sellPrice: 250,
      priceType: 'per_person',
      inclusions: 'Flight, champagne toast, certificate',
      minParticipants: 2,
    },
    {
      name: 'Mountain Bike Rental',
      category: 'rental',
      destination: 'Pokhara',
      description: 'Quality mountain bike for exploring Pokhara valley',
      duration: 'Full day',
      costPrice: 15,
      sellPrice: 25,
      priceType: 'per_person',
      inclusions: 'Bike, helmet, lock, map',
    },
    {
      name: 'Paragliding Tandem Flight',
      category: 'activity',
      destination: 'Pokhara',
      description: 'Tandem paragliding from Sarangkot with lake landing',
      duration: '30 mins flight',
      costPrice: 70,
      sellPrice: 100,
      priceType: 'per_person',
      inclusions: 'Flight, pilot, photos/video',
    },
  ];
  
  export const samplePackages = [
    {
      name: 'Everest Base Camp Trek - Classic',
      packageType: 'fixed_departure_trek',
      country: 'Nepal',
      region: 'Everest',
      durationDays: 14,
      durationNights: 13,
      difficulty: 'Challenging',
      maxAltitude: 5364,
      groupSizeMin: 2,
      groupSizeMax: 12,
      itinerarySummary: 'Fly to Lukla, trek through Namche, Tengboche, Dingboche to EBC and Kalapatthar',
      costPrice: 1200,
      sellPrice: 1650,
      singleSupplement: 300,
      inclusions: 'Flights KTM-LUA-KTM, accommodation, meals, guide, porter, permits',
      exclusions: 'Travel insurance, personal expenses, tips, bar bills',
      isFixedDeparture: true,
      departureDates: ['2025-03-15', '2025-04-01', '2025-04-15', '2025-10-01', '2025-10-15'],
    },
    {
      name: 'Annapurna Circuit Trek',
      packageType: 'fixed_departure_trek',
      country: 'Nepal',
      region: 'Annapurna',
      durationDays: 18,
      durationNights: 17,
      difficulty: 'Challenging',
      maxAltitude: 5416,
      groupSizeMin: 2,
      groupSizeMax: 12,
      itinerarySummary: 'Complete circuit around Annapurna massif crossing Thorong La Pass',
      costPrice: 1100,
      sellPrice: 1500,
      singleSupplement: 280,
      inclusions: 'Accommodation, meals, guide, porter, permits, transport',
      exclusions: 'Travel insurance, personal expenses, tips',
      isFixedDeparture: true,
      departureDates: ['2025-03-20', '2025-04-10', '2025-10-05', '2025-10-20'],
    },
    {
      name: 'Tibet Highlights Tour',
      packageType: 'tibet_tour',
      country: 'Tibet',
      region: 'Central Tibet',
      durationDays: 8,
      durationNights: 7,
      difficulty: 'Moderate',
      maxAltitude: 4500,
      groupSizeMin: 2,
      groupSizeMax: 15,
      itinerarySummary: 'Lhasa, Gyantse, Shigatse with monastery visits and cultural immersion',
      costPrice: 1400,
      sellPrice: 1900,
      singleSupplement: 350,
      inclusions: 'Permits, guide, vehicle, accommodation, breakfast',
      exclusions: 'Flights to/from Tibet, visa, other meals, tips',
      isFixedDeparture: false,
    },
    {
      name: 'Bhutan Cultural Journey',
      packageType: 'bhutan_program',
      country: 'Bhutan',
      region: 'Western Bhutan',
      durationDays: 7,
      durationNights: 6,
      difficulty: 'Easy',
      maxAltitude: 3100,
      groupSizeMin: 1,
      groupSizeMax: 12,
      itinerarySummary: 'Paro, Thimphu, Punakha with Tiger\'s Nest hike',
      costPrice: 2100,  // Bhutan has set daily tariff
      sellPrice: 2500,
      singleSupplement: 500,
      inclusions: 'SDF (Sustainable Development Fee), accommodation, all meals, guide, vehicle, permits',
      exclusions: 'Flights, visa fee, personal expenses, tips',
      isFixedDeparture: false,
    },
    {
      name: 'Everest Expedition',
      packageType: 'expedition',
      country: 'Nepal',
      region: 'Everest',
      durationDays: 60,
      durationNights: 59,
      difficulty: 'Extreme',
      maxAltitude: 8849,
      groupSizeMin: 1,
      groupSizeMax: 12,
      itinerarySummary: 'Full service Everest summit expedition with Sherpa support',
      costPrice: 35000,
      sellPrice: 45000,
      inclusions: 'Permits, Sherpa team, oxygen, camps, food, logistics',
      exclusions: 'Flights, personal gear, insurance, rescue insurance',
      isFixedDeparture: true,
      departureDates: ['2025-04-01', '2026-04-01'],
    },
  ];