// Sample seed data for all tables
// Run via API: http://localhost:3000/api/seed-all

export const sampleSuppliers = [
    { name: "Dwarika's Group", type: 'hotel', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Yeti Airlines', type: 'airline', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Himalayan Guides', type: 'guide_company', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Adventure Consultants', type: 'adventure_company', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Simrik Air', type: 'helicopter', country: 'Nepal', city: 'Kathmandu' },
    { name: 'Bhutan Tourism Corp', type: 'dmc', country: 'Bhutan', city: 'Thimphu' },
  ];
  
  export const sampleDestinations = [
    { country: 'Nepal', region: 'Kathmandu Valley', city: 'Kathmandu', altitude: 1400 },
    { country: 'Nepal', region: 'Kathmandu Valley', city: 'Bhaktapur', altitude: 1400 },
    { country: 'Nepal', region: 'Pokhara Valley', city: 'Pokhara', altitude: 827 },
    { country: 'Nepal', region: 'Everest Region', city: 'Lukla', altitude: 2860 },
    { country: 'Nepal', region: 'Everest Region', city: 'Namche Bazaar', altitude: 3440 },
    { country: 'Nepal', region: 'Annapurna Region', city: 'Jomsom', altitude: 2720 },
    { country: 'Tibet', region: 'Central Tibet', city: 'Lhasa', altitude: 3650 },
    { country: 'Bhutan', region: 'Western Bhutan', city: 'Thimphu', altitude: 2320 },
    { country: 'Bhutan', region: 'Western Bhutan', city: 'Paro', altitude: 2200 },
    { country: 'India', region: 'Sikkim', city: 'Gangtok', altitude: 1650 },
  ];
  
  export const sampleHotels = [
    {
      name: "Dwarika's Hotel",
      starRating: 5,
      category: 'Heritage Luxury',
      destinationCity: 'Kathmandu',
      description: 'Award-winning heritage hotel with traditional Newari architecture',
      amenities: ['spa', 'pool', 'gym', 'wifi', 'restaurant', 'bar'],
    },
    {
      name: 'Hotel Yak & Yeti',
      starRating: 5,
      category: 'Luxury',
      destinationCity: 'Kathmandu',
      description: 'Iconic 5-star hotel in the heart of Kathmandu',
      amenities: ['spa', 'pool', 'gym', 'wifi', 'casino', 'restaurants'],
    },
    {
      name: 'Tiger Mountain Pokhara Lodge',
      starRating: 4,
      category: 'Boutique Lodge',
      destinationCity: 'Pokhara',
      description: 'Stunning mountain views with eco-luxury experience',
      amenities: ['infinity pool', 'spa', 'yoga', 'organic garden'],
    },
    {
      name: 'Everest View Hotel',
      starRating: 3,
      category: 'Mountain Lodge',
      destinationCity: 'Namche Bazaar',
      description: 'Highest placed hotel in the world with Everest views',
      amenities: ['oxygen', 'heating', 'restaurant', 'wifi'],
    },
  ];
  
  export const sampleHotelRates = [
    // Dwarika's Hotel rates
    {
      hotelName: "Dwarika's Hotel",
      roomType: 'Heritage Deluxe',
      mealPlan: 'CP',
      costDouble: 280,
      sellDouble: 420,
      costSingle: 250,
      sellSingle: 375,
      costExtraBed: 60,
      sellExtraBed: 90,
      inclusions: 'Breakfast buffet, WiFi, Gym access, Welcome drink',
    },
    {
      hotelName: "Dwarika's Hotel",
      roomType: 'Heritage Suite',
      mealPlan: 'MAP',
      costDouble: 450,
      sellDouble: 675,
      costSingle: 400,
      sellSingle: 600,
      costExtraBed: 80,
      sellExtraBed: 120,
      inclusions: 'Breakfast & Dinner, WiFi, Spa access, Butler service',
    },
    // Tiger Mountain rates
    {
      hotelName: 'Tiger Mountain Pokhara Lodge',
      roomType: 'Deluxe Cottage',
      mealPlan: 'AP',
      costDouble: 320,
      sellDouble: 480,
      costSingle: 280,
      sellSingle: 420,
      costExtraBed: 70,
      sellExtraBed: 105,
      inclusions: 'All meals, Yoga sessions, Nature walks, WiFi',
    },
  ];
  
  export const sampleTransportation = [
    {
      vehicleType: 'sedan',
      vehicleName: 'Toyota Corolla',
      capacity: 3,
      routeFrom: 'Kathmandu',
      routeTo: 'Pokhara',
      distanceKm: 200,
      durationHours: 6,
      costPrice: 120,
      sellPrice: 180,
      inclusions: 'Fuel, driver, tolls, parking',
    },
    {
      vehicleType: 'suv',
      vehicleName: 'Toyota Fortuner',
      capacity: 5,
      routeFrom: 'Kathmandu',
      routeTo: 'Chitwan',
      distanceKm: 150,
      durationHours: 5,
      costPrice: 150,
      sellPrice: 225,
      inclusions: 'Fuel, driver, tolls, parking',
    },
    {
      vehicleType: 'hiace',
      vehicleName: 'Toyota Hiace',
      capacity: 12,
      routeFrom: 'Kathmandu',
      routeTo: 'Pokhara',
      distanceKm: 200,
      durationHours: 6,
      costPrice: 200,
      sellPrice: 300,
      inclusions: 'Fuel, driver, tolls, parking',
    },
    {
      vehicleType: 'land_cruiser',
      vehicleName: 'Toyota Land Cruiser',
      capacity: 5,
      routeFrom: 'Kathmandu',
      routeTo: 'Kodari Border',
      distanceKm: 120,
      durationHours: 4,
      costPrice: 200,
      sellPrice: 300,
      inclusions: 'Fuel, driver, tolls, permits assistance',
    },
  ];
  
  export const sampleGuides = [
    {
      guideType: 'city',
      destination: 'Kathmandu',
      languages: ['English', 'French', 'German'],
      specializations: ['Heritage', 'Buddhism', 'Hinduism'],
      experienceYears: 15,
      costPerDay: 40,
      sellPerDay: 60,
      inclusions: 'Guide service only',
      exclusions: 'Entrance fees, meals, transport',
      maxGroupSize: 15,
    },
    {
      guideType: 'trekking',
      destination: 'Everest Region',
      languages: ['English', 'Spanish'],
      specializations: ['Everest', 'High Altitude'],
      experienceYears: 12,
      costPerDay: 50,
      sellPerDay: 75,
      inclusions: 'Guide meals, accommodation, insurance',
      exclusions: 'Client meals, permits',
      maxGroupSize: 12,
    },
    {
      guideType: 'trekking',
      destination: 'Annapurna Region',
      languages: ['English', 'Japanese'],
      specializations: ['Annapurna', 'Photography'],
      experienceYears: 10,
      costPerDay: 45,
      sellPerDay: 68,
      inclusions: 'Guide meals, accommodation, insurance',
      exclusions: 'Client meals, permits',
      maxGroupSize: 10,
    },
  ];
  
  export const samplePorters = [
    {
      region: 'Everest Region',
      maxWeightKg: 25,
      costPerDay: 20,
      sellPerDay: 30,
      inclusions: 'Porter meals, accommodation, insurance',
      exclusions: 'Tips',
    },
    {
      region: 'Annapurna Region',
      maxWeightKg: 25,
      costPerDay: 18,
      sellPerDay: 27,
      inclusions: 'Porter meals, accommodation, insurance',
      exclusions: 'Tips',
    },
  ];
  
  export const sampleFlights = [
    {
      airlineName: 'Buddha Air',
      flightSector: 'KTM-LUA',
      departureCity: 'Kathmandu',
      arrivalCity: 'Lukla',
      flightDuration: '35 mins',
      baggageAllowanceKg: 15,
      costPrice: 180,
      sellPrice: 220,
      inclusions: '15kg baggage, taxes',
    },
    {
      airlineName: 'Yeti Airlines',
      flightSector: 'KTM-PKR',
      departureCity: 'Kathmandu',
      arrivalCity: 'Pokhara',
      flightDuration: '25 mins',
      baggageAllowanceKg: 20,
      costPrice: 100,
      sellPrice: 130,
      inclusions: '20kg baggage, taxes',
    },
    {
      airlineName: 'Buddha Air',
      flightSector: 'KTM-BWA',
      departureCity: 'Kathmandu',
      arrivalCity: 'Bhairahawa',
      flightDuration: '30 mins',
      baggageAllowanceKg: 20,
      costPrice: 120,
      sellPrice: 150,
      inclusions: '20kg baggage, taxes',
    },
  ];
  
  export const sampleHelicopterSharing = [
    {
      routeName: 'Everest Base Camp Heli Tour',
      routeFrom: 'Kathmandu',
      routeTo: 'Everest Base Camp',
      flightDuration: '4-5 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      seatsAvailable: 5,
      minPassengers: 4,
      costPerSeat: 900,
      sellPerSeat: 1100,
      inclusions: 'Hotel pickup, Kalapatthar landing, breakfast at Everest View Hotel, all permits',
    },
    {
      routeName: 'Annapurna Base Camp Heli Tour',
      routeFrom: 'Pokhara',
      routeTo: 'Annapurna Base Camp',
      flightDuration: '2-3 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      seatsAvailable: 5,
      minPassengers: 4,
      costPerSeat: 600,
      sellPerSeat: 750,
      inclusions: 'Hotel pickup, ABC landing, all permits',
    },
  ];
  
  export const sampleHelicopterCharter = [
    {
      routeName: 'Everest Base Camp Charter',
      routeFrom: 'Kathmandu',
      routeTo: 'Everest Base Camp',
      flightDuration: '4-5 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      maxPassengers: 5,
      costPerCharter: 4000,
      sellPerCharter: 5200,
      inclusions: 'Exclusive charter, Kalapatthar landing, breakfast at Everest View Hotel, all permits',
    },
    {
      routeName: 'Langtang Valley Charter',
      routeFrom: 'Kathmandu',
      routeTo: 'Kyanjin Gompa',
      flightDuration: '2-3 hours total',
      helicopterType: 'Eurocopter AS350 B3',
      maxPassengers: 5,
      costPerCharter: 2800,
      sellPerCharter: 3600,
      inclusions: 'Exclusive charter, monastery visit, all permits',
    },
  ];
  
  export const samplePermitsFees = [
    {
      name: 'TIMS Card',
      type: 'permit',
      country: 'Nepal',
      applicableTo: 'foreigners',
      costPrice: 20,
      sellPrice: 25,
      description: 'Trekkers Information Management System card required for all treks',
    },
    {
      name: 'Sagarmatha National Park Entry',
      type: 'entrance_fee',
      country: 'Nepal',
      region: 'Everest',
      applicableTo: 'foreigners',
      costPrice: 30,
      sellPrice: 35,
      description: 'Entry permit for Everest region (Sagarmatha National Park)',
    },
    {
      name: 'Annapurna Conservation Area Permit',
      type: 'conservation',
      country: 'Nepal',
      region: 'Annapurna',
      applicableTo: 'foreigners',
      costPrice: 30,
      sellPrice: 35,
      description: 'ACAP permit for Annapurna region trekking',
    },
    {
      name: 'Tibet Travel Permit',
      type: 'permit',
      country: 'Tibet',
      applicableTo: 'foreigners',
      costPrice: 100,
      sellPrice: 120,
      description: 'Required permit for foreigners to visit Tibet',
      processingTime: '15-20 days',
    },
  ];
  
  export const sampleMiscellaneous = [
    {
      name: 'Nepalese Dinner with Cultural Show',
      category: 'dining',
      destination: 'Kathmandu',
      description: 'Traditional Nepali cuisine with live music and dance performances',
      duration: '3 hours',
      costPrice: 35,
      sellPrice: 55,
      priceType: 'per_person',
      inclusions: 'Multi-course dinner, cultural performances, welcome drink',
    },
    {
      name: 'Dinner with Local Family',
      category: 'experience',
      destination: 'Kathmandu',
      description: 'Authentic home-cooked meal with a local Newari family',
      duration: '3-4 hours',
      costPrice: 40,
      sellPrice: 65,
      priceType: 'per_person',
      minParticipants: 2,
      inclusions: 'Home-cooked meal, cooking demonstration, cultural exchange',
    },
    {
      name: 'Celebrity Chef Dinner',
      category: 'dining',
      destination: 'Kathmandu',
      description: 'Exclusive dining experience with renowned local chef',
      duration: '4 hours',
      costPrice: 120,
      sellPrice: 180,
      priceType: 'per_person',
      minParticipants: 4,
      inclusions: '7-course tasting menu, wine pairing, meet the chef',
    },
    {
      name: 'Phewa Lake Boating',
      category: 'activity',
      destination: 'Pokhara',
      description: 'Scenic rowboat ride on Phewa Lake with mountain views',
      duration: '1-2 hours',
      costPrice: 10,
      sellPrice: 18,
      priceType: 'per_person',
      inclusions: 'Boat rental, life jacket',
    },
    {
      name: 'Hot Air Balloon Flight',
      category: 'activity',
      destination: 'Pokhara',
      description: 'Sunrise balloon flight with Himalayan panorama',
      duration: '1 hour flight',
      costPrice: 180,
      sellPrice: 250,
      priceType: 'per_person',
      inclusions: 'Flight, champagne toast, certificate',
      minParticipants: 2,
    },
    {
      name: 'Mountain Bike Rental',
      category: 'rental',
      destination: 'Pokhara',
      description: 'Quality mountain bike for exploring Pokhara valley',
      duration: 'Full day',
      costPrice: 15,
      sellPrice: 25,
      priceType: 'per_person',
      inclusions: 'Bike, helmet, lock, map',
    },
    {
      name: 'Paragliding Tandem Flight',
      category: 'activity',
      destination: 'Pokhara',
      description: 'Tandem paragliding from Sarangkot with lake landing',
      duration: '30 mins flight',
      costPrice: 70,
      sellPrice: 100,
      priceType: 'per_person',
      inclusions: 'Flight, pilot, photos/video',
    },
  ];
  
  export const samplePackages = [
    {
      slug: 'everest-base-camp-trek-classic',
      name: 'Everest Base Camp Trek - Classic',
      packageType: 'fixed_departure_trek',
      country: 'Nepal',
      region: 'Everest',
      durationDays: 14,
      durationNights: 13,
      difficulty: 'Challenging',
      maxAltitude: 5364,
      groupSizeMin: 2,
      groupSizeMax: 12,
      itinerarySummary: 'Fly to Lukla, trek through Namche, Tengboche, Dingboche to EBC and Kalapatthar',
      costPrice: 1200,
      sellPrice: 1650,
      singleSupplement: 300,
      inclusions: 'Flights KTM-LUA-KTM, accommodation, meals, guide, porter, permits',
      exclusions: 'Travel insurance, personal expenses, tips, bar bills',
      isFixedDeparture: true,
      departureDates: ['2025-03-15', '2025-04-01', '2025-04-15', '2025-10-01', '2025-10-15'],
    },
    {
      slug: 'annapurna-circuit-trek',
      name: 'Annapurna Circuit Trek',
      packageType: 'fixed_departure_trek',
      country: 'Nepal',
      region: 'Annapurna',
      durationDays: 18,
      durationNights: 17,
      difficulty: 'Challenging',
      maxAltitude: 5416,
      groupSizeMin: 2,
      groupSizeMax: 12,
      itinerarySummary: 'Complete circuit around Annapurna massif crossing Thorong La Pass',
      costPrice: 1100,
      sellPrice: 1500,
      singleSupplement: 280,
      inclusions: 'Accommodation, meals, guide, porter, permits, transport',
      exclusions: 'Travel insurance, personal expenses, tips',
      isFixedDeparture: true,
      departureDates: ['2025-03-20', '2025-04-10', '2025-10-05', '2025-10-20'],
    },
    {
      slug: 'tibet-highlights-tour',
      name: 'Tibet Highlights Tour',
      packageType: 'tibet_tour',
      country: 'Tibet',
      region: 'Central Tibet',
      durationDays: 8,
      durationNights: 7,
      difficulty: 'Moderate',
      maxAltitude: 4500,
      groupSizeMin: 2,
      groupSizeMax: 15,
      itinerarySummary: 'Lhasa, Gyantse, Shigatse with monastery visits and cultural immersion',
      costPrice: 1400,
      sellPrice: 1900,
      singleSupplement: 350,
      inclusions: 'Permits, guide, vehicle, accommodation, breakfast',
      exclusions: 'Flights to/from Tibet, visa, other meals, tips',
      isFixedDeparture: false,
    },
    {
      slug: 'bhutan-cultural-journey',
      name: 'Bhutan Cultural Journey',
      packageType: 'bhutan_program',
      country: 'Bhutan',
      region: 'Western Bhutan',
      durationDays: 7,
      durationNights: 6,
      difficulty: 'Easy',
      maxAltitude: 3100,
      groupSizeMin: 1,
      groupSizeMax: 12,
      itinerarySummary: 'Paro, Thimphu, Punakha with Tiger\'s Nest hike',
      costPrice: 2100,  // Bhutan has set daily tariff
      sellPrice: 2500,
      singleSupplement: 500,
      inclusions: 'SDF (Sustainable Development Fee), accommodation, all meals, guide, vehicle, permits',
      exclusions: 'Flights, visa fee, personal expenses, tips',
      isFixedDeparture: false,
    },
    {
      slug: 'everest-expedition',
      name: 'Everest Expedition',
      packageType: 'expedition',
      country: 'Nepal',
      region: 'Everest',
      durationDays: 60,
      durationNights: 59,
      difficulty: 'Extreme',
      maxAltitude: 8849,
      groupSizeMin: 1,
      groupSizeMax: 12,
      itinerarySummary: 'Full service Everest summit expedition with Sherpa support',
      costPrice: 35000,
      sellPrice: 45000,
      inclusions: 'Permits, Sherpa team, oxygen, camps, food, logistics',
      exclusions: 'Flights, personal gear, insurance, rescue insurance',
      isFixedDeparture: true,
      departureDates: ['2025-04-01', '2026-04-01'],
    },
    // --- Curated Itineraries with full day-by-day details ---
    {
      slug: '14-day-nepal-luxury-expedition',
      name: '14-Day Nepal Luxury Expedition',
      packageType: 'fixed_departure_trek',
      country: 'Nepal',
      region: 'Kathmandu, Chitwan, Pokhara, Annapurna',
      durationDays: 14,
      durationNights: 13,
      difficulty: 'Moderate',
      maxAltitude: 3210,
      groupSizeMin: 2,
      groupSizeMax: 8,
      itinerarySummary: 'Journey through the heart of Nepal — from the ancient temples of Kathmandu to the jungles of Chitwan, the lakes of Pokhara, and the foothills of the Annapurna range. This expedition balances cultural immersion with adventure, all wrapped in five-star comfort.',
      costPrice: 3000,
      sellPrice: 4500,
      singleSupplement: 600,
      inclusions: 'All domestic flights (Kathmandu–Chitwan–Pokhara–Kathmandu), Private helicopter flight over Annapurna range, 13 nights luxury accommodation, All meals as indicated (full board on trek/safari days), Private English-speaking guide throughout, All national park entrance fees and permits, Private airport transfers and ground transportation, Poon Hill trek with sherpa guide and porters, Full-day Chitwan safari (jeep + canoe), Ayurvedic spa treatment in Pokhara, Cooking class and cultural performances, 24/7 on-trip support',
      exclusions: 'International flights to/from Kathmandu, Travel insurance (required), Nepal visa fee ($50 USD on arrival), Optional paragliding in Pokhara, Personal expenses and gratuities, Alcoholic beverages beyond welcome/farewell dinners',
      isFixedDeparture: false,
      itineraryDetailed: {
        highlights: [
          'Private helicopter flight over the Annapurna range',
          'Sunrise over the Himalayas from Sarangkot',
          'Tiger tracking in Chitwan National Park',
          'UNESCO World Heritage temples in Kathmandu Valley',
          'Luxury lakeside resort stay in Pokhara',
          'Traditional Newari cooking class with a local family',
        ],
        bestMonths: 'Mar–May, Sep–Nov',
        route: 'Kathmandu → Chitwan → Pokhara → Annapurna Foothills → Kathmandu',
        days: [
          { day: 1, title: 'Arrival in Kathmandu', description: "Private airport transfer to your heritage hotel. Afternoon orientation walk through Thamel. Welcome dinner at Krishnarpan, Dwarika's celebrated Newari fine-dining restaurant, set within the hotel's restored brick courtyards.", accommodation: "Dwarika's Hotel, Kathmandu", meals: 'Dinner' },
          { day: 2, title: 'Kathmandu Valley Heritage', description: 'Private guided tour of Boudhanath Stupa, Pashupatinath Temple, and Patan Durbar Square. Afternoon Newari cooking class with a local family.', accommodation: "Dwarika's Hotel, Kathmandu", meals: 'Breakfast, Lunch, Dinner' },
          { day: 3, title: 'Bhaktapur & Nagarkot', description: 'Explore the medieval city of Bhaktapur. Drive to Nagarkot for sunset views stretching from Everest to Annapurna across the entire Himalayan range.', accommodation: 'Club Himalaya, Nagarkot', meals: 'Breakfast, Lunch, Dinner' },
          { day: 4, title: 'Fly to Chitwan', description: 'Morning mountain sunrise. Scenic flight to Bharatpur, then private transfer to your luxury jungle lodge on the banks of the Rapti River, bordering Chitwan National Park.', accommodation: 'Meghauli Serai (Taj), Chitwan', meals: 'Breakfast, Lunch, Dinner' },
          { day: 5, title: 'Chitwan Safari', description: 'Dawn canoe ride along the Rapti River. Full-day jeep safari to track Bengal tigers, one-horned rhinoceros, and elephants. Evening Tharu cultural performance.', accommodation: 'Meghauli Serai (Taj), Chitwan', meals: 'Breakfast, Lunch, Dinner' },
          { day: 6, title: 'Chitwan to Pokhara', description: 'Morning birdwatching walk. Scenic overland drive through river valleys and terraced hillsides to Pokhara.', accommodation: 'Tiger Mountain Pokhara Lodge', meals: 'Breakfast, Lunch, Dinner' },
          { day: 7, title: 'Pokhara at Leisure', description: 'Sunrise excursion to Sarangkot viewpoint. Afternoon boating on Phewa Lake with Annapurna reflections. Optional paragliding over the valley.', accommodation: 'Tiger Mountain Pokhara Lodge', meals: 'Breakfast, Dinner' },
          { day: 8, title: 'Annapurna Helicopter Flight', description: 'Private helicopter flight over the Annapurna range, landing at a high-altitude viewpoint for champagne breakfast with a panoramic Himalayan backdrop.', accommodation: 'Tiger Mountain Pokhara Lodge', meals: 'Breakfast, Lunch, Dinner' },
          { day: 9, title: 'Poon Hill Trek Day 1', description: 'Drive to Nayapul and begin the trek through rhododendron forests to Ghorepani. Experienced sherpa guide and porters carry all equipment.', accommodation: 'Mountain Lodge, Ghorepani', meals: 'Breakfast, Lunch, Dinner' },
          { day: 10, title: 'Poon Hill Sunrise & Descent', description: 'Pre-dawn hike to Poon Hill (3,210m) for the iconic 360° panorama of Dhaulagiri, Annapurna, and Machhapuchhre. Trek back to Pokhara.', accommodation: 'Tiger Mountain Pokhara Lodge', meals: 'Breakfast, Lunch, Dinner' },
          { day: 11, title: 'Pokhara Wellness Day', description: 'Morning yoga session. Full Ayurvedic spa treatment. Afternoon visit to the International Mountain Museum and lakeside gallery walk.', accommodation: 'Tiger Mountain Pokhara Lodge', meals: 'Breakfast, Dinner' },
          { day: 12, title: 'Return to Kathmandu', description: 'Scenic flight back to Kathmandu. Afternoon at leisure for shopping in Thamel or exploring hidden courtyards of the old city.', accommodation: "Dwarika's Hotel, Kathmandu", meals: 'Breakfast, Dinner' },
          { day: 13, title: 'Kathmandu Final Exploration', description: 'Visit Swayambhunath (Monkey Temple) and the Garden of Dreams. Farewell gala dinner at a historic Rana palace with traditional dance.', accommodation: "Dwarika's Hotel, Kathmandu", meals: 'Breakfast, Dinner' },
          { day: 14, title: 'Departure', description: 'Private transfer to Tribhuvan International Airport. Complimentary departure lounge access.', accommodation: '—', meals: 'Breakfast' },
        ],
      },
    },
    {
      slug: '10-day-bhutan-cultural-immersion',
      name: '10-Day Bhutan Cultural Immersion',
      packageType: 'bhutan_program',
      country: 'Bhutan',
      region: 'Paro, Thimphu, Punakha, Gangtey',
      durationDays: 10,
      durationNights: 9,
      difficulty: 'Easy to Moderate',
      maxAltitude: 3120,
      groupSizeMin: 2,
      groupSizeMax: 6,
      itinerarySummary: "Discover the world's last Himalayan kingdom — a land where Gross National Happiness matters more than GDP. From the cliffside Tiger's Nest monastery to the pristine Gangtey Valley, this journey reveals Bhutan's spiritual depth, stunning architecture, and untouched landscapes.",
      costPrice: 4133,
      sellPrice: 6200,
      singleSupplement: 800,
      inclusions: "9 nights luxury accommodation (Amankora lodges + Gangtey Lodge), Bhutan Sustainable Development Fee (SDF), All meals (full board throughout), Private licensed Bhutanese guide, All monastery and dzong entrance fees, Private ground transportation, Tiger's Nest hike with packed lunch, Hot stone bath experience, Private audience with Buddhist monk, Airport transfers, 24/7 on-trip support",
      exclusions: 'International flights to/from Paro, Bhutan visa fee ($40 USD), Travel insurance (required), Personal expenses and gratuities, Alcoholic beverages, Optional helicopter excursions',
      isFixedDeparture: false,
      itineraryDetailed: {
        highlights: [
          "Hike to Tiger's Nest (Taktsang) Monastery",
          'Private audience with a Buddhist monk',
          'Stay at Amankora luxury lodges',
          "Punakha Dzong — Bhutan's most beautiful fortress",
          'Black-necked crane sanctuary in Gangtey Valley',
          'Traditional hot stone bath experience',
        ],
        bestMonths: 'Mar–May, Sep–Nov',
        route: 'Paro → Thimphu → Punakha → Gangtey → Paro',
        days: [
          { day: 1, title: 'Arrival in Paro', description: "One of the world's most dramatic landings between Himalayan peaks. Private transfer to your lodge. Afternoon walk through Paro town and visit to Rinpung Dzong.", accommodation: 'Amankora Paro', meals: 'Lunch, Dinner' },
          { day: 2, title: "Tiger's Nest Hike", description: 'The iconic hike to Taktsang Monastery (3,120m), perched on a sheer cliff 900m above the valley floor. Stop at the hillside cafeteria for tea with valley views.', accommodation: 'Amankora Paro', meals: 'Breakfast, Lunch, Dinner', altitude: '3,120m' },
          { day: 3, title: 'Paro to Thimphu', description: 'Drive to the capital Thimphu. Visit the National Memorial Chorten, the giant Buddha Dordenma statue, and the traditional textile museum. Evening stroll along the riverside.', accommodation: 'Amankora Thimphu', meals: 'Breakfast, Lunch, Dinner' },
          { day: 4, title: 'Thimphu Cultural Day', description: 'Morning visit to Tashichho Dzong. Afternoon at the Folk Heritage Museum and paper-making workshop. Private audience with a Buddhist monk at a local monastery.', accommodation: 'Amankora Thimphu', meals: 'Breakfast, Lunch, Dinner' },
          { day: 5, title: 'Thimphu to Punakha', description: 'Cross the Dochula Pass (3,100m) with views of snow-capped peaks and 108 memorial chortens. Descend to the subtropical Punakha Valley.', accommodation: 'Amankora Punakha', meals: 'Breakfast, Lunch, Dinner', altitude: '3,100m pass' },
          { day: 6, title: 'Punakha Valley', description: "Visit Punakha Dzong at the confluence of two rivers — Bhutan's most magnificent fortress. Afternoon riverside picnic and hike to Khamsum Yulley Namgyal Chorten.", accommodation: 'Amankora Punakha', meals: 'Breakfast, Lunch, Dinner' },
          { day: 7, title: 'Punakha to Gangtey', description: 'Drive through oak and rhododendron forests to the glacial Gangtey (Phobjikha) Valley. Visit the 17th-century Gangtey Goenpa monastery.', accommodation: 'Gangtey Lodge', meals: 'Breakfast, Lunch, Dinner' },
          { day: 8, title: 'Gangtey Valley Exploration', description: 'Nature walk through the valley — home to the rare black-necked crane (winter months). Visit local farmhouses and try traditional Bhutanese archery.', accommodation: 'Gangtey Lodge', meals: 'Breakfast, Lunch, Dinner' },
          { day: 9, title: 'Return to Paro', description: 'Scenic drive back to Paro. Afternoon traditional hot stone bath (Dotsho) — an ancient Bhutanese wellness ritual. Farewell dinner with local music and dance.', accommodation: 'Amankora Paro', meals: 'Breakfast, Lunch, Dinner' },
          { day: 10, title: 'Departure', description: 'Morning at leisure. Private transfer to Paro International Airport for departure.', accommodation: '—', meals: 'Breakfast' },
        ],
      },
    },
    {
      slug: '12-day-india-himalayan-explorer',
      name: '12-Day India Himalayan Explorer',
      packageType: 'india_program',
      country: 'India',
      region: 'Delhi, Rishikesh, Mussoorie, Ladakh',
      durationDays: 12,
      durationNights: 11,
      difficulty: 'Moderate to Challenging',
      maxAltitude: 5359,
      groupSizeMin: 2,
      groupSizeMax: 8,
      itinerarySummary: "From the spiritual banks of the Ganges to the high passes of Ladakh, this expedition traverses India's most spectacular Himalayan landscapes. Experience ashram yoga, British-era hill stations, ancient monasteries, and the otherworldly beauty of the Changthang plateau.",
      costPrice: 2533,
      sellPrice: 3800,
      singleSupplement: 500,
      inclusions: 'All domestic flights (Delhi–Leh and Leh–Delhi), 11 nights luxury accommodation, All meals as indicated, Private English-speaking guide throughout, Private yoga session in Rishikesh, Ayurvedic spa treatment at Ananda, All monument entrance fees and permits, Inner Line Permits for Ladakh restricted areas, Private ground transportation including 4x4 in Ladakh, Bactrian camel ride in Nubra Valley, Airport transfers, 24/7 on-trip support and oxygen cylinder in Ladakh',
      exclusions: 'International flights to/from Delhi, India e-Visa fee, Travel insurance (required — must cover high altitude), Personal expenses and gratuities, Alcoholic beverages, Optional white-water rafting in Rishikesh',
      isFixedDeparture: false,
      itineraryDetailed: {
        highlights: [
          'Sunrise Ganga Aarti ceremony in Rishikesh',
          'Private yoga session at a riverside ashram',
          "Khardung La — one of the world's highest motorable passes",
          'Buddhist monasteries of Ladakh (Hemis, Thiksey)',
          'Pangong Lake — the iconic turquoise high-altitude lake',
          'Colonial heritage walk in Mussoorie',
        ],
        bestMonths: 'May–Jun, Sep–Oct',
        route: 'Delhi → Rishikesh → Mussoorie → Ladakh → Delhi',
        days: [
          { day: 1, title: 'Arrival in Delhi', description: "Private airport transfer to your heritage hotel. Evening orientation walk through Lutyens' Delhi and welcome dinner.", accommodation: 'The Imperial, New Delhi', meals: 'Dinner' },
          { day: 2, title: 'Delhi Heritage Tour', description: 'Private guided tour of Old Delhi — Jama Masjid, Red Fort, Chandni Chowk rickshaw ride. Afternoon visit to Humayun\'s Tomb and Qutub Minar.', accommodation: 'The Imperial, New Delhi', meals: 'Breakfast, Lunch' },
          { day: 3, title: 'Delhi to Rishikesh', description: 'Drive to Rishikesh along the Ganges. Continue up to Ananda, a palatial hilltop estate overlooking the Ganges valley. Evening excursion to Triveni Ghat for the Ganga Aarti — a mesmerizing fire ritual on the riverbank.', accommodation: 'Ananda in the Himalayas', meals: 'Breakfast, Dinner' },
          { day: 4, title: 'Rishikesh — Yoga & Spirituality', description: 'Sunrise yoga session at a riverside ashram. Visit the Beatles Ashram. Afternoon Ayurvedic spa treatment at Ananda.', accommodation: 'Ananda in the Himalayas', meals: 'Breakfast, Lunch, Dinner' },
          { day: 5, title: 'Rishikesh to Mussoorie', description: 'Drive to the British hill station of Mussoorie. Afternoon heritage walk along the Mall Road and Gun Hill viewpoint.', accommodation: 'JW Marriott Mussoorie', meals: 'Breakfast, Dinner' },
          { day: 6, title: 'Mussoorie & Dhanaulti', description: "Morning excursion to Dhanaulti's cedar forests. Afternoon tea at a colonial estate. Optional nature walk through Eco Park.", accommodation: 'JW Marriott Mussoorie', meals: 'Breakfast, Lunch' },
          { day: 7, title: 'Fly to Ladakh', description: "Early transfer to Dehradun airport for connecting flight to Leh via Delhi. Arrive in Leh (3,500m) by afternoon. Rest and acclimatize. Gentle evening walk through Leh's old town.", accommodation: 'The Grand Dragon, Leh', meals: 'Breakfast, Dinner', altitude: '3,500m' },
          { day: 8, title: 'Leh Monastery Circuit', description: "Visit Thiksey Monastery (mini Potala), Hemis Monastery (Ladakh's largest), and Shey Palace. Afternoon at leisure for acclimatization.", accommodation: 'The Grand Dragon, Leh', meals: 'Breakfast, Lunch', altitude: '3,500m' },
          { day: 9, title: 'Khardung La & Nubra Valley', description: 'Drive over Khardung La (5,359m). Descend into the stunning Nubra Valley. Ride double-humped Bactrian camels in the sand dunes of Hunder.', accommodation: 'Nubra Ecolodge', meals: 'Breakfast, Lunch, Dinner', altitude: '5,359m pass' },
          { day: 10, title: 'Nubra to Pangong Lake', description: 'Drive along the Shyok River road through dramatic gorges, past Durbuk and Tangtse, to reach Pangong Tso — a breathtaking turquoise lake stretching into Tibet. Watch the colors shift at sunset.', accommodation: 'Pangong Retreat Camp', meals: 'Breakfast, Lunch, Dinner', altitude: '4,350m' },
          { day: 11, title: 'Return to Leh', description: 'Morning photography at Pangong. Drive back to Leh via Chang La. Farewell dinner at a Ladakhi restaurant.', accommodation: 'The Grand Dragon, Leh', meals: 'Breakfast, Lunch, Dinner' },
          { day: 12, title: 'Departure via Delhi', description: 'Morning flight Leh to Delhi. Private transfer and complimentary airport lounge access for international connection.', accommodation: '—', meals: 'Breakfast' },
        ],
      },
    },
    {
      slug: '8-day-tibet-sacred-lands',
      name: '8-Day Tibet Sacred Lands',
      packageType: 'tibet_tour',
      country: 'Tibet',
      region: 'Lhasa, Gyantse, Shigatse, Everest North',
      durationDays: 8,
      durationNights: 7,
      difficulty: 'Moderate to Challenging',
      maxAltitude: 5200,
      groupSizeMin: 2,
      groupSizeMax: 6,
      itinerarySummary: "Traverse the Roof of the World — from the golden-roofed Potala Palace in Lhasa to the north face of Everest. This journey follows the ancient route through Tibet's most sacred monasteries, dramatic passes, and high-altitude landscapes that few travellers ever witness.",
      costPrice: 3667,
      sellPrice: 5500,
      singleSupplement: 700,
      inclusions: 'Tibet Travel Permit and all restricted-area permits, 7 nights accommodation, All meals (full board throughout), Private licensed Tibetan guide, Private 4x4 vehicle with experienced driver, All monastery and monument entrance fees, Everest Base Camp National Park fee, Supplemental oxygen and first-aid kit, Airport transfers in Lhasa, 24/7 on-trip support',
      exclusions: 'International flights to/from Lhasa (via Chengdu or Kathmandu), Chinese visa and Tibet Travel Permit processing fee, Travel insurance (required — must cover high altitude and evacuation), Personal expenses and gratuities, Alcoholic beverages, Optional Namtso Lake extension',
      isFixedDeparture: false,
      itineraryDetailed: {
        highlights: [
          'Potala Palace — the iconic 13-story fortress of the Dalai Lamas',
          'Jokhang Temple and Barkhor kora pilgrimage circuit',
          "Gyantse Kumbum — Tibet's largest stupa",
          'Everest Base Camp (North) — 5,200m viewpoint',
          'Yamdrok Lake — sacred turquoise lake at 4,441m',
          'Tashilhunpo Monastery in Shigatse',
        ],
        bestMonths: 'Apr–Jun, Sep–Oct',
        route: 'Lhasa → Gyantse → Shigatse → Everest North Base Camp → Lhasa',
        days: [
          { day: 1, title: 'Arrival in Lhasa', description: "Fly into Lhasa Gonggar Airport (3,650m). Private transfer with supplemental oxygen available. Rest and acclimatize — gentle evening walk along Lhasa's river promenade.", accommodation: 'St. Regis Lhasa', meals: 'Dinner', altitude: '3,650m' },
          { day: 2, title: 'Lhasa — Potala Palace & Jokhang', description: 'Morning visit to the magnificent Potala Palace, winter residence of the Dalai Lamas. Afternoon exploration of Jokhang Temple and the bustling Barkhor kora circuit.', accommodation: 'St. Regis Lhasa', meals: 'Breakfast, Lunch, Dinner', altitude: '3,650m' },
          { day: 3, title: 'Lhasa Monasteries', description: 'Visit Sera Monastery to witness the famous debating monks. Afternoon at Drepung Monastery, once the world\'s largest monastery housing over 10,000 monks. Evening Tibetan opera performance.', accommodation: 'St. Regis Lhasa', meals: 'Breakfast, Lunch, Dinner', altitude: '3,650m' },
          { day: 4, title: 'Lhasa to Gyantse via Yamdrok Lake', description: 'Drive over Kamba La pass (4,700m) to the sacred Yamdrok Lake — its turquoise waters stretching endlessly below. Continue to the historic town of Gyantse.', accommodation: 'Gyantse Hotel', meals: 'Breakfast, Lunch, Dinner', altitude: '4,700m pass → 3,977m' },
          { day: 5, title: 'Gyantse to Shigatse', description: "Morning visit to Gyantse Kumbum — Tibet's most spectacular stupa, with six floors housing 77 chapels adorned with ancient murals. Drive to Shigatse and explore Tashilhunpo Monastery.", accommodation: 'Shigatse Hotel', meals: 'Breakfast, Lunch, Dinner', altitude: '3,840m' },
          { day: 6, title: 'Shigatse to Everest Base Camp', description: "Epic drive across the Tibetan Plateau, crossing multiple passes above 5,000m. Arrive at Rongbuk Monastery — the highest in the world — with Everest's north face towering above.", accommodation: 'Everest Base Camp Guesthouse', meals: 'Breakfast, Lunch, Dinner', altitude: '5,200m' },
          { day: 7, title: 'Everest & Return to Shigatse', description: "Sunrise over Everest's north face (weather permitting). Time at Everest Base Camp North (5,200m). Return drive to Shigatse. Farewell dinner with traditional Tibetan dishes.", accommodation: 'Shigatse Hotel', meals: 'Breakfast, Lunch, Dinner', altitude: '5,200m → 3,840m' },
          { day: 8, title: 'Return to Lhasa & Departure', description: 'Drive back to Lhasa (or fly from Shigatse Peace Airport if available). Transfer to Lhasa Gonggar Airport for departure.', accommodation: '—', meals: 'Breakfast', altitude: '3,650m' },
        ],
      },
    },
  ];