import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { blogPosts, blogCategories, destinations, blogSocialPosts } from "@/db/schema";
import { eq } from "drizzle-orm";

export const dynamic = "force-dynamic";

// GET - Get single blog post by ID
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const postId = parseInt(id);

    if (isNaN(postId)) {
      return NextResponse.json(
        { error: "Invalid post ID" },
        { status: 400 }
      );
    }

    const [post] = await db
      .select({
        id: blogPosts.id,
        title: blogPosts.title,
        slug: blogPosts.slug,
        content: blogPosts.content,
        excerpt: blogPosts.excerpt,
        featuredImage: blogPosts.featuredImage,
        featuredImageAlt: blogPosts.featuredImageAlt,
        gallery: blogPosts.gallery,
        metaTitle: blogPosts.metaTitle,
        metaDescription: blogPosts.metaDescription,
        keywords: blogPosts.keywords,
        tags: blogPosts.tags,
        status: blogPosts.status,
        authorName: blogPosts.authorName,
        publishedAt: blogPosts.publishedAt,
        scheduledAt: blogPosts.scheduledAt,
        contentType: blogPosts.contentType,
        readTimeMinutes: blogPosts.readTimeMinutes,
        viewCount: blogPosts.viewCount,
        shareCount: blogPosts.shareCount,
        isAutoGenerated: blogPosts.isAutoGenerated,
        promptUsed: blogPosts.promptUsed,
        version: blogPosts.version,
        createdAt: blogPosts.createdAt,
        updatedAt: blogPosts.updatedAt,
        categoryId: blogPosts.categoryId,
        categoryName: blogCategories.name,
        categorySlug: blogCategories.slug,
        destinationId: blogPosts.destinationId,
        destinationCountry: destinations.country,
        destinationCity: destinations.city,
      })
      .from(blogPosts)
      .leftJoin(blogCategories, eq(blogPosts.categoryId, blogCategories.id))
      .leftJoin(destinations, eq(blogPosts.destinationId, destinations.id))
      .where(eq(blogPosts.id, postId))
      .limit(1);

    if (!post) {
      return NextResponse.json(
        { error: "Post not found" },
        { status: 404 }
      );
    }

    // Get social posts for this blog post
    const socialPosts = await db
      .select()
      .from(blogSocialPosts)
      .where(eq(blogSocialPosts.blogPostId, postId));

    return NextResponse.json({
      success: true,
      post: {
        ...post,
        socialPosts,
      },
    });
  } catch (error) {
    console.error("Error fetching blog post:", error);
    return NextResponse.json(
      { error: "Failed to fetch blog post" },
      { status: 500 }
    );
  }
}

// PUT - Update blog post
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const postId = parseInt(id);

    if (isNaN(postId)) {
      return NextResponse.json(
        { error: "Invalid post ID" },
        { status: 400 }
      );
    }

    const body = await request.json();
    const {
      title,
      slug,
      content,
      excerpt,
      categoryId,
      destinationId,
      featuredImage,
      featuredImageAlt,
      gallery,
      metaTitle,
      metaDescription,
      keywords,
      tags,
      status,
      authorName,
      scheduledAt,
      contentType,
      readTimeMinutes,
    } = body;

    // Check if post exists
    const [existingPost] = await db
      .select()
      .from(blogPosts)
      .where(eq(blogPosts.id, postId))
      .limit(1);

    if (!existingPost) {
      return NextResponse.json(
        { error: "Post not found" },
        { status: 404 }
      );
    }

    // Check slug uniqueness if changed
    if (slug && slug !== existingPost.slug) {
      const [slugExists] = await db
        .select({ id: blogPosts.id })
        .from(blogPosts)
        .where(eq(blogPosts.slug, slug))
        .limit(1);

      if (slugExists) {
        return NextResponse.json(
          { error: "A post with this slug already exists" },
          { status: 400 }
        );
      }
    }

    // Build update object
    const updateData: Record<string, unknown> = {
      updatedAt: new Date(),
    };

    if (title !== undefined) updateData.title = title;
    if (slug !== undefined) updateData.slug = slug;
    if (content !== undefined) {
      updateData.content = content;
      updateData.readTimeMinutes = readTimeMinutes || calculateReadTime(content);
    }
    if (excerpt !== undefined) updateData.excerpt = excerpt;
    if (categoryId !== undefined) updateData.categoryId = categoryId || null;
    if (destinationId !== undefined) updateData.destinationId = destinationId || null;
    if (featuredImage !== undefined) updateData.featuredImage = featuredImage;
    if (featuredImageAlt !== undefined) updateData.featuredImageAlt = featuredImageAlt;
    if (gallery !== undefined) updateData.gallery = gallery;
    if (metaTitle !== undefined) updateData.metaTitle = metaTitle;
    if (metaDescription !== undefined) updateData.metaDescription = metaDescription;
    if (keywords !== undefined) updateData.keywords = keywords;
    if (tags !== undefined) updateData.tags = tags;
    if (authorName !== undefined) updateData.authorName = authorName;
    if (scheduledAt !== undefined) updateData.scheduledAt = scheduledAt ? new Date(scheduledAt) : null;
    if (contentType !== undefined) updateData.contentType = contentType;
    if (readTimeMinutes !== undefined) updateData.readTimeMinutes = readTimeMinutes;

    // Handle status changes
    if (status !== undefined) {
      updateData.status = status;
      if (status === "published" && existingPost.status !== "published") {
        updateData.publishedAt = new Date();
      }
    }

    // Increment version
    updateData.version = (existingPost.version || 1) + 1;

    const [updatedPost] = await db
      .update(blogPosts)
      .set(updateData)
      .where(eq(blogPosts.id, postId))
      .returning();

    return NextResponse.json({
      success: true,
      post: updatedPost,
    });
  } catch (error) {
    console.error("Error updating blog post:", error);
    return NextResponse.json(
      { error: "Failed to update blog post" },
      { status: 500 }
    );
  }
}

// DELETE - Delete blog post
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const postId = parseInt(id);

    if (isNaN(postId)) {
      return NextResponse.json(
        { error: "Invalid post ID" },
        { status: 400 }
      );
    }

    // Delete associated social posts first
    await db
      .delete(blogSocialPosts)
      .where(eq(blogSocialPosts.blogPostId, postId));

    // Delete the blog post
    const [deletedPost] = await db
      .delete(blogPosts)
      .where(eq(blogPosts.id, postId))
      .returning({ id: blogPosts.id });

    if (!deletedPost) {
      return NextResponse.json(
        { error: "Post not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      message: "Post deleted successfully",
    });
  } catch (error) {
    console.error("Error deleting blog post:", error);
    return NextResponse.json(
      { error: "Failed to delete blog post" },
      { status: 500 }
    );
  }
}

function calculateReadTime(content: string): number {
  const wordsPerMinute = 200;
  const wordCount = content.split(/\s+/).length;
  return Math.ceil(wordCount / wordsPerMinute);
}
