import { NextResponse } from "next/server";
import { db } from "@/db";
import { blogPosts, blogCategories, blogSocialPosts } from "@/db/schema";
import { eq, sql, desc } from "drizzle-orm";

export const dynamic = "force-dynamic";

// GET - Blog analytics aggregated data
export async function GET() {
  try {
    // Summary stats
    const [summary] = await db
      .select({
        totalPosts: sql<number>`count(*)::int`,
        publishedPosts: sql<number>`count(*) filter (where ${blogPosts.status} = 'published')::int`,
        totalViews: sql<number>`coalesce(sum(${blogPosts.viewCount}), 0)::int`,
        avgReadTime: sql<number>`coalesce(round(avg(${blogPosts.readTimeMinutes})), 0)::int`,
        aiGenerated: sql<number>`count(*) filter (where ${blogPosts.isAutoGenerated} = true)::int`,
        manualCreated: sql<number>`count(*) filter (where ${blogPosts.isAutoGenerated} = false or ${blogPosts.isAutoGenerated} is null)::int`,
      })
      .from(blogPosts);

    // Posts over time (by month, last 12 months)
    const postsOverTime = await db
      .select({
        month: sql<string>`to_char(${blogPosts.createdAt}, 'YYYY-MM')`,
        count: sql<number>`count(*)::int`,
      })
      .from(blogPosts)
      .where(sql`${blogPosts.createdAt} >= now() - interval '12 months'`)
      .groupBy(sql`to_char(${blogPosts.createdAt}, 'YYYY-MM')`)
      .orderBy(sql`to_char(${blogPosts.createdAt}, 'YYYY-MM')`);

    // Views over time (by month, last 12 months — using publishedAt for published posts)
    const viewsOverTime = await db
      .select({
        month: sql<string>`to_char(coalesce(${blogPosts.publishedAt}, ${blogPosts.createdAt}), 'YYYY-MM')`,
        views: sql<number>`coalesce(sum(${blogPosts.viewCount}), 0)::int`,
      })
      .from(blogPosts)
      .where(sql`${blogPosts.createdAt} >= now() - interval '12 months'`)
      .groupBy(sql`to_char(coalesce(${blogPosts.publishedAt}, ${blogPosts.createdAt}), 'YYYY-MM')`)
      .orderBy(sql`to_char(coalesce(${blogPosts.publishedAt}, ${blogPosts.createdAt}), 'YYYY-MM')`);

    // Top 10 posts by views
    const topPosts = await db
      .select({
        id: blogPosts.id,
        title: blogPosts.title,
        viewCount: blogPosts.viewCount,
        publishedAt: blogPosts.publishedAt,
        contentType: blogPosts.contentType,
      })
      .from(blogPosts)
      .where(eq(blogPosts.status, "published"))
      .orderBy(desc(blogPosts.viewCount))
      .limit(10);

    // Category distribution
    const categoryDist = await db
      .select({
        categoryId: blogPosts.categoryId,
        categoryName: blogCategories.name,
        categoryColor: blogCategories.color,
        count: sql<number>`count(*)::int`,
      })
      .from(blogPosts)
      .leftJoin(blogCategories, eq(blogPosts.categoryId, blogCategories.id))
      .groupBy(blogPosts.categoryId, blogCategories.name, blogCategories.color);

    // Content type distribution
    const contentTypeDist = await db
      .select({
        contentType: blogPosts.contentType,
        count: sql<number>`count(*)::int`,
      })
      .from(blogPosts)
      .groupBy(blogPosts.contentType);

    // Social media performance by platform
    const socialPerformance = await db
      .select({
        platform: blogSocialPosts.platform,
        total: sql<number>`count(*)::int`,
        published: sql<number>`count(*) filter (where ${blogSocialPosts.status} = 'published')::int`,
        failed: sql<number>`count(*) filter (where ${blogSocialPosts.status} = 'failed')::int`,
        totalImpressions: sql<number>`coalesce(sum(${blogSocialPosts.impressions}), 0)::int`,
        totalClicks: sql<number>`coalesce(sum(${blogSocialPosts.clicks}), 0)::int`,
      })
      .from(blogSocialPosts)
      .groupBy(blogSocialPosts.platform);

    return NextResponse.json({
      summary,
      postsOverTime,
      viewsOverTime,
      topPosts,
      categoryDistribution: categoryDist,
      contentTypeDistribution: contentTypeDist,
      socialPerformance,
    });
  } catch (error) {
    console.error("Blog analytics error:", error);
    return NextResponse.json(
      { error: "Failed to fetch blog analytics" },
      { status: 500 }
    );
  }
}
